### ISSUE TITLE
Testbot - Implement Flight Assistant

### ISSUE THREAD

**Issue by matiasroldan6** [southworkscom/botbuilder-js#50]
## Description
Help reduce the gap between the JS and .NET versions by implementing the Flight Assistant Testbot in the tests for Botbuilder-JS

## Details
Right now there's implemented only an Echobot in the tests for the library. It would be good to implement the Flight Assistant TestBot so increase parity with .NET.
If we take a look at the code in .NET we can see in [Startup.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Startup.cs#L59):

![image](https://user-images.githubusercontent.com/20074735/59125642-5133c800-8939-11e9-864b-24bfbf48504f.png)
that there are many types of bots initialized depending on the specified endpoint. The top bot (_myBot_) is an Echobot that is [already implemented in JS](https://github.com/microsoft/botbuilder-js/blob/master/libraries/testbot/bots/myBot.js) 

It would be nice to continue by implementing the following bot, the Flight Assistant. This is shown in the above image as [DialogBot](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Bots/DialogBot.cs) and it takes a [MainDialog](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs) as the type.

It's required to to implement the DialogBot as one of the bots that are already in `/libraries/testbot/bots/` and its corresponding MainDialog.

Here's how the Flight Assistant bot is running right now in the .NET library:
![image](https://user-images.githubusercontent.com/20074735/59126794-4b8bb180-893c-11e9-9920-55b711105e25.png)

![image](https://user-images.githubusercontent.com/20074735/59126856-770e9c00-893c-11e9-90ac-a3eb667b1428.png)

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi, just some minor feedback:

- Replace the tile `Implement Flight Assistant Testbot` for `Testbot - Implement Flight Assistant`
- After the second image, in the `several types of bots initialized depending on a key` text, replace `on a key` with `the specified endpoint` (remember that this works with the BotController, which can handle any kind of endpoint matching `api/{botName}`)

**Comment by Aliandi** [comment]
- `It would be good to get closer to what Botbuilder-dotnet is to start by implementing a Flight Assistant Testbot.` -> `It would be good to implement the Flight Assistant TestBot so increase pairity with .NET`
- `several types of bots initialized depending...` -> `that there are many types of bots initialized depending...`
- `The top bot (myBot) is an Echobot which is already implemented in JS` -> `The top bot (myBot) is an Echobot that is already implemented in JS`
- `It would be nice to continue by implementing the following bot, the Flight Assistant. This is shown in the above image as DialogBot and it takes a MainDialog as the type`  -> missing period at the end of the sentence
- `The request is to` -> `It's required to`
- `The request is to implement the DialogBot as one of the bots that are already in /libraries/testbot/bots/ and its corresponding MainDialog ~in order to more closely resemble the state of the library in .NET.~`

**Comment by GasparAcevedoZainSouthworks** [comment]
Replaced w/MS #974
